name: Cleanup

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cleanup artifacts and folders
      run: |
        rm -rf bin obj publish