name: Full CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  buildmy:
    uses: ./.github/workflows/build_my.yml

  cleanup:
    needs: build
    uses: ./.github/workflows/cleanup.yml

  analyze:
    needs: cleanup
    uses: ./.github/workflows/codeql.yml

  build:
    needs: analyze
    uses: ./.github/workflows/dotnet.yml