name: Full CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    uses: ./.github/workflows/build.yml

  cleanup:
    needs: build
    uses: ./.github/workflows/cleanup.yml

  analyze:
    needs: cleanup
    uses: ./.github/workflows/codeql.yml

