name: Full CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    uses: ./.github/workflows/build.yml

  zip:
    needs: build
    uses: ./.github/workflows/zip.yml

  cleanup:
    needs: build
    uses: ./.github/workflows/cleanup.yml

  runIt:
    needs: cleanup
    uses: ./.github/workflows/run.yml


