name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Extract version from AppConfig.cs
      id: get_version
      run: |
        VERSION=$(grep 'public static string Version' dev/Core/AppConfig.cs | grep -oE '[0-9]+\.[0-9]+[a-zA-Z0-9]*')
        echo "VERSION_TAG=$VERSION" >> $GITHUB_ENV

    - name: Build project for Linux
      run: dotnet publish ServerNetworkAPI.csproj -c Release -r linux-x64 --self-contained true -o ./publish/linux