name: Deploy

on:
    workflow_dispatch: 
    workflow_call:       

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upload to remote server via SCP
      run: |
        scp publish/zip/ServerNetworkAPI.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock