name: runIt

on:
  workflow_dispatch:
  workflow_call:

jobs:
  runIt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y arp-scan nmap

    - name: Make executable
      run: chmod +x ./publish/linux/ServerNetworkAPI

    - name: Run ServerNetworkAPI for 120s and log output
      run: |
        if [ "$GITHUB_ACTIONS" == "true" ]; then
          echo "Running inside GitHub Actions Runner"
        else
          echo "Not running inside GitHub Actions. Exiting."
          exit 1
        fi

        ./publish/linux/ServerNetworkAPI --headless --nmap  run120.log 2>&1 &
        PID=$!
        echo "Started with PID $PID"
        sleep 10

        if ps -p $PID > /dev/null; then
          echo "Process is still running after 10s. Continuing to wait."
          sleep 110
          kill -SIGINT $PID
          echo "Sent SIGINT to process"
        else
          echo "::error ::Process $PID already exited. Probably crashed."
          cat run120.log
          exit 1
        fi

    - name: Show full log of run120.log
      run: |
        echo "========== FULL LOG: run120.log =========="
        cat run120.log || echo "run120.log not found."
