name: runIt

on:
  workflow_dispatch:
  workflow_call:

jobs:
  runIt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make executable
      run: chmod +x ./publish/linux/ServerNetworkAPI

    - name: Run ServerNetworkAPI for 120s and log output
      run: |
        ./publish/linux/ServerNetworkAPI --nmap > run120.log 2>&1 &
        PID=$!
        echo "Started with PID: $PID"
        sleep 120
        kill -SIGINT $PID
        echo "Sent SIGINT to process"

    - name: Run ServerNetworkAPI for 360s and log output
      run: |
        ./publish/linux/ServerNetworkAPI --nmap > run360.log 2>&1 &
        PID=$!
        echo "Started with PID: $PID"
        sleep 360
        kill -SIGINT $PID
        echo "Sent SIGINT to process"

    - name: Show full log of run120.log
      run: |
        echo "========== FULL LOG: run120.log =========="
        cat run120.log || echo "run120.log not found."

    - name: Show full log of run360.log
      run: |
        echo "========== FULL LOG: run360.log =========="
        cat run360.log || echo "run360.log not found."



